# dokodemo常用于 测试。 它可将任意程序的输出转发到 特定目标地址

# 本示例测试udp, 对应的 客户端程序为 doco_udpclient.go , 使用 go run doco_udpclient.go 运行它,
# 然后运行本配置, 你在 doco_udpclient.go 输入的所有字符串都会被 本配置发送到 10800, 并让10800进一步发送到 4444

[[listen]]
protocol = "dokodemo"
network = "udp" # 可以监听tcp，也可以监听 udp
host = "127.0.0.1"
port = 63782
target = "udp://127.0.0.1:4444" 
#target = "udp://2620:1ec:c11::200:4444" #该ipv6只是作为一个示范. 目的是告诉你，在这里不用中括号

#关于不用中括号的规定，只在 在url中填充 ipv6地址时存在。这是因为，url中如果填写了中括号的话，会被golang转义为百分号，导致代码处理错误

[[dial]]
protocol = "socks5"
#protocol = "shadowsocks"
host = "127.0.0.1"
port = 10800
#uuid = "method:AES-128-GCM\npass:iloveverysimple"   
