[[listen]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4434
insecure = true
fallback = ":80"
cert = "cert.pem"
key = "cert.key"

advancedLayer = "grpc"
path = "verysimple_serviceName"


[listen.header.request]

headers.Mycustom1 = ["verysimple_is_so_good"]

[listen.header.response]

headers.mycustom2 = ["i_agree"]

[[dial]]
protocol = "direct"
