
[[listen]]
protocol = "vmesss"    #注意末尾的s, 这在vs中意味着使用tls. 
# 另外注意在vs中，与shadowTls一起使用的必须是具有内层加密的协议，不能用trojan或vless, 否则就是裸奔

tag = "t"
host = "cloud.tecent.com"   #假域名, 两端要配置为一致的。 一般用 www.microsoft.com 等常见大型公司的
ip = "127.0.0.1"
port = 4433 #我们这里为了测试使用4433端口，你如果实际用，改成443 更隐蔽
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
tls_type = "shadowTls2" # v1 写成 shadowTls1 ，但有2了谁用1呢

#extra = { tls_minVersion = "1.2",tls_maxVersion = "1.2" }  # 用于 shadowTls v1

extra.shadowtls_password = "a684455c-b14f-11ea-bf0d-42010aaa0003"  # 用于 shadowTls v2

# 回落测试命令: curl -vik --resolve cloud.tecent.com:443:127.0.0.1 https://cloud.tecent.com

# 当然，你要把上面的port 配置改为443，同时确保本机没有其他程序在使用443, 然后用 sudo 运行 vs.

extra.tls_rejectUnknownSni = true # 这个开启了的话，防御效果更佳, vs已经做了针对性优化。

