[[listen]]
tag = "my_vlesss1"
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "0.0.0.0"
port = 4433
version = -1 # 因为服务端需要同时兼容 v0客户端 和 v1客户端. 如果你指定了1，那就意味着只支持 v1 的客户端. 指定了0，那就意味着只支持 v0客户端，所以只有 指定为-1，程序才能明白 【你想全支持】

insecure = true
fallback = ":80" 
cert = "cert.pem"
key = "cert.key"

[[dial]]
tag = "mydirect"
protocol = "direct"
# fullcone = true   # 默认的fullcone是关闭状态, 可以取消注释以打开

[[route]]
fromTag = ["my_vlesss1"]
toTag = "mydirect"
