[[listen]]
protocol = "socks5"
host = "127.0.0.1"
port = 10800


[[dial]]
protocol = "vlesss"
uuid = "a684455c-b14f-11ea-bf0d-42010aaa0003"
host = "127.0.0.1"
port = 4434
version = 0
insecure = true
#tls_type = "utls"
adv = "ws"
path = "/ohmygod_verysimple_is_very_simple" 

#为了防探测, path越长越随机越好, 而且path项必须给出, 如果要为空, 写成 path = "/"


# early = true    # 是否开启early data, 注意本作这里要开启的话，就要服务端和客户端 两端都开启。
