version: "3.3"
services:
  verysimple:
    container_name: verysimple
    restart: always
    network_mode: "host"
    volumes:
      - "/etc/verysimple:/etc/verysimple_files"
    command: -path /etc/verysimple_files
    image: ghcr.io/e1732a364fed/v2ray_simple:latest
