name: Build aar

on:
  workflow_dispatch:

jobs:
  build_job1:
    name: build aar
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
              
      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12

      - name: Run genaar.sh
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          export PATH=$PATH:~/go/bin
          gomobile init
          cd machine
          chmod +x genaar.sh
          ./genaar.sh

      - name: Generate Artifact
        uses: actions/upload-artifact@v3
        with:
          name: xx.aar
          path: machine/xx.aar
